#10: Added a module for code coverage in UDFs
exasol/udf-debugging-java pull request #12
Opened 2020-11-20 08:52 UTC by jakobbraun

Closes #10

2020-11-22 21:57 UTC, morazow requested changes

2020-11-22 21:57 UTC, morazow commented on README.md
> +This module requires some maven configuration. Use the [project-keeper's](https://github.com/exasol/project-keeper-maven-plugin) `udf_coverage` module to verify it.
```suggestion
This module requires additional maven configuration. Use the [project-keeper's](https://github.com/exasol/project-keeper-maven-plugin) `udf_coverage` module to verify it.   
```

2020-11-22 21:57 UTC, morazow commented on doc/changes/changes_0.3.0.md
> +# udf-debugging-java 0.3.0, released 2020-11-20
Please do not forget to change the date.

2020-11-22 21:57 UTC, morazow commented on doc/changes/changes_0.3.0.md
> +* Updated `com:exasol:project-keeper-maven-plugin`:0.2.0 to 0.3.0
From the internal discussion, I think we agreed on this format:
```
Updated to `com:exasol:project-keeper-maven-plugin:0.3.0` (was 0.2.0)
```

2020-11-22 21:57 UTC, morazow commented on doc/changes/changes_0.3.0.md
> +* Updated `com:exasol:project-keeper-maven-plugin`:0.2.0 to 0.3.0
Please feel free to change it.

2020-11-22 21:57 UTC, morazow commented on src/main/java/com/exasol/udfdebugging/modules/coverage/CoverageModule.java
> +            Thread.currentThread().interrupt();
:+1:

2020-11-23 07:25 UTC, morazow approved these changes
Approved. 
There seems to be some Sonar issues.

2020-11-23 07:47 UTC, jakobbraun commented
only coverage.

2020-11-23 08:45 UTC, merged